name: Docker
on:
  push:
    branches: "main"
  pull_request:
  workflow_dispatch: # allows you to trigger manually
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true
env:
  MY_GCR_NAMESPACE: 'juliaparallel'
  MY_GCR_IMAGENAME: 'dask-jobqueue-ci-images'
permissions:
  contents: read
  packages: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        clustermanager:
          - htcondor
          - pbs
          - sge
          - slurm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: docker version
        run: |
          which -a docker
          docker version
          docker compose version
      - name: docker compose build
        run: |
          cd "./ci/${MATRIX_CLUSTERMANAGER:?}"
          cp ../environment.yml environment.yml
          docker compose build
        env:
          MATRIX_CLUSTERMANAGER: ${{ matrix.clustermanager }}
      - name: List images
        run: |
          docker ps -a
          docker images
      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish HTCondor images
        if: matrix.clustermanager == 'htcondor' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          docker push "ghcr.io/${MY_GCR_NAMESPACE:?}/${MY_GCR_IMAGENAME:?}:${MATRIX_CLUSTERMANAGER:?}-submit"
          docker push "ghcr.io/${MY_GCR_NAMESPACE:?}/${MY_GCR_IMAGENAME:?}:${MATRIX_CLUSTERMANAGER:?}-execute"
        env:
          MATRIX_CLUSTERMANAGER: ${{ matrix.clustermanager }}
      - name: Publish most images (but not HTCondor)
        if: matrix.clustermanager != 'htcondor' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          docker push "ghcr.io/${MY_GCR_NAMESPACE:?}/${MY_GCR_IMAGENAME:?}:${MATRIX_CLUSTERMANAGER:?}"
        env:
          MATRIX_CLUSTERMANAGER: ${{ matrix.clustermanager }}
      - name: Publish secondary SGE images
        if: matrix.clustermanager == 'sge' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          docker push "ghcr.io/${MY_GCR_NAMESPACE:?}/${MY_GCR_IMAGENAME:?}:${MATRIX_CLUSTERMANAGER:?}-slave"
        env:
          MATRIX_CLUSTERMANAGER: ${{ matrix.clustermanager }}
